const bodyParser = require('body-parser')
const express = require('express')
const bodyparser = require('body-parser')
const cors = require('cors')
const sequelize = require('./util/dataBase')
const app = express()
const expenseRouter = require('./router/expense')
app.use(bodyparser.json())
app.use(cors())
app.use('/',expenseRouter)
sequelize.sync()
app.listen(3000)